site_name: Tenderfoot's Blog
site_url: https://G-Tenderfoot.github.io
site_author: Tenderfoot
theme:
  name: material #主题
  custom_dir: docs/overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  include_search_page: false
  search_index_only: true
  favicon: 'favicon.ico'
  icon:
    logo: 'material/school'

  features: 
    - announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    - navigation.instant 
    #- header.autohide  #自动隐藏
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    # - navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    - navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - navigation.footer #页脚将呈现在边栏中，但在移动设备上保持原样
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - search.share #搜索分享按钮
    - navigation.expand # 打开Tab时左侧目录全部展开
    - navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - content.tabs.link
    - content.tooltips
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.code.annotate 
  language: zh # 一些提示性的文字会变成中文

copyright: 'Copyright &copy; 2024-2024 Tenderfoot'

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - 简介:
    - Getting Started: intro/Blogindex.md
    - 可能进行的项目: intro/projects.md
  - 抽象代数:
    - 唯一分解整环:
      - 唯一分解整环: Abstract algebra/2.2.md
      - 单变元多项式: Abstract algebra/2.3.md
  - 常微分方程:
    - 概念及一阶常微分方程:
      - 概念: ODE/1.1.md
  - 一些概念的理解:
    - 抽象代数:
      - 商群与理想: Understanding/商群与理想.md
      - Galois理论概述: Understanding/Galois理论概述/Galois理论概述.md 
        - 引言: Understanding/Galois理论概述/Galois_0.md 
  - 杂项:
    - Test 1: others/Test 1.md
    - Test 2: others/Test 2.md


